#!/usr/bin/env bash
# Reproducible verification-evidence harness. Runs EVERY assurance tier and writes a single
# evidence report the CAB / certification scheme can pin (docs/certification-evidence/README.md
# lists the wider evidence set; this is the machine-verifiable core of it, plan Section 10/11/12).
#
#   Tier 1  implementation conformance  — cargo test (real crypto, sans-IO core)
#   Tier 2  state-machine proofs         — Lean models machine-checked + oracle→Rust conformance
#   Tier 3  protocol analysis            — Tamarin symbolic models (Dolev-Yao)
#   Lint    — clippy -D warnings across the workspace
#   ZK      — the experimental Ristretto proof (feature-gated, non-production)
#
# Usage:  tools/evidence/generate.sh   (writes docs/certification-evidence/verification-report.md)
# Exit non-zero if ANY tier fails, so CI gates on it.
set -uo pipefail
cd "$(dirname "$0")/../.."
export PATH="/opt/homebrew/opt/rustup/bin:/opt/homebrew/bin:$HOME/.cargo/bin:$HOME/.elan/bin:$PATH"

REPORT="docs/certification-evidence/verification-report.md"
FAIL=0
LEAN_MODELS=(WalletModel PaymentModel ProximityModel IssuanceModel QesModel W2wModel)
TAMARIN_MODELS=(oid4vp_haip payment_sca iso18013_5_proximity oid4vci_issuance qes w2w)

pass() { echo "PASS"; }
fail() { echo "FAIL"; FAIL=1; }

echo "# Verification evidence report" > "$REPORT"
echo >> "$REPORT"
echo "Generated by \`tools/evidence/generate.sh\`. Every row is reproducible from a clean checkout." >> "$REPORT"
echo "This is the machine-verifiable core of the certification evidence set (see this directory's README)." >> "$REPORT"
echo >> "$REPORT"

# --- Tier 1: implementation conformance ---
echo "## Tier 1 — implementation conformance (cargo test, real aws-lc-rs crypto)" >> "$REPORT"
echo >> "$REPORT"
T1=$(cargo test --workspace 2>&1)
T1_COUNT=$(echo "$T1" | grep 'test result: ok' | sed -E 's/.*ok\. ([0-9]+) passed.*/\1/' | awk '{s+=$1} END{print s}')
if echo "$T1" | grep -q 'test result: FAILED' || [ -z "$T1_COUNT" ]; then T1_R=$(fail); else T1_R=$(pass); fi
echo "| Metric | Value |" >> "$REPORT"
echo "|---|---|" >> "$REPORT"
echo "| Workspace tests passed | ${T1_COUNT:-0} |" >> "$REPORT"
echo "| Result | **$T1_R** |" >> "$REPORT"
echo >> "$REPORT"

# --- Tier 2: Lean proofs (machine-checked) ---
echo "## Tier 2 — state-machine proofs (Lean, machine-checked) + oracle→Rust conformance" >> "$REPORT"
echo >> "$REPORT"
echo "| Model | \`lake build\` |" >> "$REPORT"
echo "|---|---|" >> "$REPORT"
( cd formal/lean && lake build "${LEAN_MODELS[@]}" >/tmp/lean.log 2>&1 )
LEAN_OK=$?
for m in "${LEAN_MODELS[@]}"; do
  if [ $LEAN_OK -eq 0 ]; then echo "| $m | PASS |" >> "$REPORT"; else echo "| $m | FAIL |" >> "$REPORT"; FAIL=1; fi
done
echo >> "$REPORT"
echo "Oracle→Rust conformance suites (each replays the Lean oracle's traces through the Rust mirror) run under Tier 1: \`crates/{oid4vp,payment,iso18013-5,oid4vci,qes,w2w}/tests/conformance.rs\`." >> "$REPORT"
echo >> "$REPORT"

# --- Tier 3: Tamarin symbolic analysis ---
echo "## Tier 3 — protocol analysis (Tamarin, Dolev-Yao attacker)" >> "$REPORT"
echo >> "$REPORT"
if command -v tamarin-prover >/dev/null 2>&1; then
  echo "| Model | Lemmas verified | Falsified |" >> "$REPORT"
  echo "|---|---|---|" >> "$REPORT"
  for m in "${TAMARIN_MODELS[@]}"; do
    OUT=$(tamarin-prover --prove "formal/tamarin/$m.spthy" 2>/dev/null)
    V=$(echo "$OUT" | grep -c 'verified')
    F=$(echo "$OUT" | grep -c 'falsified')
    echo "| $m | $V | $F |" >> "$REPORT"
    if [ "$F" -ne 0 ] || [ "$V" -eq 0 ]; then FAIL=1; fi
  done
else
  echo "> tamarin-prover not on PATH — Tier 3 skipped. Install: \`brew install tamarin-prover/tap/tamarin-prover\`." >> "$REPORT"
fi
echo >> "$REPORT"

# --- Lint ---
echo "## Lint — clippy \`-D warnings\` (workspace)" >> "$REPORT"
echo >> "$REPORT"
if cargo clippy --workspace --all-targets -- -D warnings >/tmp/clippy.log 2>&1; then CL=$(pass); else CL=$(fail); fi
echo "Result: **$CL**" >> "$REPORT"
echo >> "$REPORT"

# --- ZK experimental ---
echo "## Experimental ZK (feature \`experimental-zk\`, non-production)" >> "$REPORT"
echo >> "$REPORT"
ZK=$(cargo test -p zkp --features experimental-zk 2>&1)
ZK_COUNT=$(echo "$ZK" | grep 'test result: ok' | sed -E 's/.*ok\. ([0-9]+) passed.*/\1/' | awk '{s+=$1} END{print s}')
if echo "$ZK" | grep -q 'test result: FAILED'; then ZK_R=$(fail); else ZK_R=$(pass); fi
echo "Ristretto Pedersen/Schnorr proof tests passed: ${ZK_COUNT:-0} — **$ZK_R** (behind \`PROFILE_EXPERIMENTAL\`; production default is the selective-disclosure fallback)." >> "$REPORT"
echo >> "$REPORT"

echo "---" >> "$REPORT"
if [ $FAIL -eq 0 ]; then
  echo "**Overall: PASS** — all assurance tiers green." >> "$REPORT"
else
  echo "**Overall: FAIL** — at least one tier did not pass; see the rows above." >> "$REPORT"
fi

echo "Report written to $REPORT"
[ $FAIL -eq 0 ] && echo "OVERALL: PASS" || echo "OVERALL: FAIL"
exit $FAIL
