#!/usr/bin/env bash
# Reproducible verification-evidence harness. Runs every automated assurance check and writes a
# single report. A passing report records successful execution; it is not a certification claim.
#
# Usage: tools/evidence/generate.sh
# Set REPORT to write somewhere other than the checked-in report (useful for validation).
set -uo pipefail
cd "$(dirname "$0")/../.." || exit 1
DEFAULT_PATH_PREFIX="/opt/homebrew/opt/rustup/bin:/opt/homebrew/bin:$HOME/.cargo/bin:$HOME/.elan/bin"
PATH_PREFIX="${EVIDENCE_PATH_PREFIX-$DEFAULT_PATH_PREFIX}"
if [ -n "$PATH_PREFIX" ]; then
  export PATH="$PATH_PREFIX:$PATH"
fi

REPORT="${REPORT:-docs/certification-evidence/verification-report.md}"
FAIL=0
LEAN_MODELS=(WalletModel PaymentModel ProximityModel IssuanceModel QesModel W2wModel NavigationModel)
LEAN_TRACES=(
  "traces|crates/oid4vp/tests/model_traces.json"
  "payment_traces|crates/payment/tests/model_traces.json"
  "proximity_traces|crates/iso18013-5/tests/model_traces.json"
  "issuance_traces|crates/oid4vci/tests/model_traces.json"
  "qes_traces|crates/qes/tests/model_traces.json"
  "w2w_traces|crates/w2w/tests/model_traces.json"
)
CONFORMANCE_PACKAGES=(oid4vp payment iso18013-5 oid4vci qes w2w)
TAMARIN_MODELS=(oid4vp_haip payment_sca iso18013_5_proximity oid4vci_issuance qes w2w)

mark_failure() {
  FAIL=1
}

count_passed_tests() {
  sed -nE 's/.*test result: ok\. ([0-9]+) passed.*/\1/p' "$1" |
    awk '{ total += $1; rows += 1 } END { if (rows > 0) print total }'
}

if ! mkdir -p "$(dirname "$REPORT")"; then
  echo "Unable to create the report directory for $REPORT" >&2
  exit 1
fi

LOG_DIR=$(mktemp -d "${TMPDIR:-/tmp}/euwallet-evidence.XXXXXX") || exit 1
trap 'rm -rf "$LOG_DIR"' EXIT

{
  echo "# Verification evidence report"
  echo
  echo "Generated by \`tools/evidence/generate.sh\` from executable checks in this checkout."
  echo "A PASS means these automated checks ran successfully; it does not establish full HLR coverage, regulatory approval, or wallet certification."
  echo
} > "$REPORT"

# --- Tier 0: requirement traceability ---
{
  echo "## Tier 0 — requirement traceability (harmonized EUDI register → implementation)"
  echo
} >> "$REPORT"

TRACE_RESULT=FAIL
TRACE_SUMMARY="Traceability mapping did not run."
if ! command -v python3 >/dev/null 2>&1; then
  TRACE_SUMMARY="Required tool missing: python3."
  mark_failure
elif TRACE_OUTPUT=$(python3 tools/evidence/map_traceability.py 2>&1); then
  TRACE_RESULT=PASS
  TRACE_SUMMARY=$(printf '%s\n' "$TRACE_OUTPUT" | head -n 1)
else
  TRACE_SUMMARY="Traceability mapping returned an error."
  printf '%s\n' "$TRACE_OUTPUT" > "$LOG_DIR/traceability.log"
  mark_failure
fi
{
  echo "$TRACE_SUMMARY"
  echo
  echo "Result: **$TRACE_RESULT**"
  echo
  echo "Mappings are generated by keyword rules and identify candidate implementation and test links. Unmapped requirements remain \`unassigned\`; mapped rows still require certification review."
  echo
} >> "$REPORT"

# --- Tier 1: implementation conformance ---
{
  echo "## Tier 1 — implementation conformance (cargo test, real aws-lc-rs crypto)"
  echo
} >> "$REPORT"

T1_RESULT=FAIL
T1_COUNT=0
if ! command -v cargo >/dev/null 2>&1; then
  echo "Required tool missing: cargo." > "$LOG_DIR/cargo-test.log"
  mark_failure
elif cargo test --workspace --locked > "$LOG_DIR/cargo-test.log" 2>&1; then
  T1_COUNT=$(count_passed_tests "$LOG_DIR/cargo-test.log")
  if [ "${T1_COUNT:-0}" -gt 0 ]; then
    T1_RESULT=PASS
  else
    mark_failure
  fi
else
  T1_COUNT=$(count_passed_tests "$LOG_DIR/cargo-test.log")
  mark_failure
fi
{
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Workspace tests passed | ${T1_COUNT:-0} |"
  echo "| Result | **$T1_RESULT** |"
  echo
} >> "$REPORT"

# --- Tier 2: Lean proofs and oracle replay ---
{
  echo "## Tier 2 — state-machine proofs (Lean, machine-checked) + oracle→Rust conformance"
  echo
  echo "| Model | \`lake build\` |"
  echo "|---|---|"
} >> "$REPORT"

if command -v lake >/dev/null 2>&1; then
  for model in "${LEAN_MODELS[@]}"; do
    if (cd formal/lean && lake build "$model") > "$LOG_DIR/lean-$model.log" 2>&1; then
      echo "| $model | PASS |" >> "$REPORT"
    else
      echo "| $model | FAIL |" >> "$REPORT"
      mark_failure
    fi
  done
else
  for model in "${LEAN_MODELS[@]}"; do
    echo "| $model | FAIL — required tool missing: lake |" >> "$REPORT"
  done
  mark_failure
fi

{
  echo
  echo "| Oracle executable | Checked-in trace is current |"
  echo "|---|---|"
} >> "$REPORT"

for trace_spec in "${LEAN_TRACES[@]}"; do
  IFS='|' read -r executable fixture <<< "$trace_spec"
  trace_output="$LOG_DIR/$executable.json"
  trace_result=FAIL
  if command -v lake >/dev/null 2>&1 &&
      (cd formal/lean && lake exe "$executable") > "$trace_output" 2> "$LOG_DIR/$executable.log"; then
    if cmp -s "$trace_output" "$fixture"; then
      trace_result=PASS
    else
      mark_failure
    fi
  else
    mark_failure
  fi
  echo "| $executable | $trace_result |" >> "$REPORT"
done

{
  echo
  echo "| Rust oracle replay | Result |"
  echo "|---|---|"
} >> "$REPORT"

for package in "${CONFORMANCE_PACKAGES[@]}"; do
  conformance_result=FAIL
  if command -v cargo >/dev/null 2>&1 &&
      cargo test --locked -p "$package" --test conformance > "$LOG_DIR/conformance-$package.log" 2>&1; then
    conformance_result=PASS
  else
    mark_failure
  fi
  echo "| $package | $conformance_result |" >> "$REPORT"
done
echo >> "$REPORT"

# --- Tier 3: Tamarin symbolic analysis ---
{
  echo "## Tier 3 — protocol analysis (Tamarin, Dolev-Yao attacker)"
  echo
  echo "| Model | Lemmas verified | Falsified | Result |"
  echo "|---|---|---|---|"
} >> "$REPORT"

if command -v tamarin-prover >/dev/null 2>&1; then
  for model in "${TAMARIN_MODELS[@]}"; do
    tamarin_log="$LOG_DIR/tamarin-$model.log"
    tamarin_result=FAIL
    if tamarin-prover --prove "formal/tamarin/$model.spthy" > "$tamarin_log" 2>&1; then
      tamarin_exit=0
    else
      tamarin_exit=$?
    fi
    verified=$(grep -c 'verified' "$tamarin_log")
    falsified=$(grep -c 'falsified' "$tamarin_log")
    verified=${verified:-0}
    falsified=${falsified:-0}
    if [ "$tamarin_exit" -eq 0 ] && [ "$verified" -gt 0 ] && [ "$falsified" -eq 0 ]; then
      tamarin_result=PASS
    else
      mark_failure
    fi
    echo "| $model | $verified | $falsified | $tamarin_result |" >> "$REPORT"
  done
else
  for model in "${TAMARIN_MODELS[@]}"; do
    echo "| $model | 0 | 0 | FAIL — required tool missing: tamarin-prover |" >> "$REPORT"
  done
  mark_failure
fi
echo >> "$REPORT"

# --- Lint ---
{
  echo "## Lint — clippy \`-D warnings\` (workspace)"
  echo
} >> "$REPORT"
CLIPPY_RESULT=FAIL
if command -v cargo >/dev/null 2>&1 &&
    cargo clippy --workspace --all-targets --locked -- -D warnings > "$LOG_DIR/clippy.log" 2>&1; then
  CLIPPY_RESULT=PASS
else
  mark_failure
fi
{
  echo "Result: **$CLIPPY_RESULT**"
  echo
} >> "$REPORT"

# --- ZK experimental ---
{
  echo "## Experimental ZK (feature \`experimental-zk\`, non-production)"
  echo
} >> "$REPORT"
ZK_RESULT=FAIL
ZK_COUNT=0
if command -v cargo >/dev/null 2>&1 &&
    cargo test --locked -p zkp --features experimental-zk > "$LOG_DIR/zk.log" 2>&1; then
  ZK_COUNT=$(count_passed_tests "$LOG_DIR/zk.log")
  if [ "${ZK_COUNT:-0}" -gt 0 ]; then
    ZK_RESULT=PASS
  else
    mark_failure
  fi
else
  if [ -f "$LOG_DIR/zk.log" ]; then
    ZK_COUNT=$(count_passed_tests "$LOG_DIR/zk.log")
  fi
  mark_failure
fi
{
  echo "Ristretto Pedersen/Schnorr proof tests passed: ${ZK_COUNT:-0} — **$ZK_RESULT** (behind \`PROFILE_EXPERIMENTAL\`; production default is the selective-disclosure fallback)."
  echo
  echo "---"
} >> "$REPORT"

if [ "$FAIL" -eq 0 ]; then
  echo "**Automated verification result: PASS** — every required tool was present and every configured executable check passed. This is not a wallet certification decision." >> "$REPORT"
else
  echo "**Automated verification result: FAIL** — at least one required tool was missing or one configured check failed; no verification claim should be made from this run." >> "$REPORT"
fi

echo "Report written to $REPORT"
if [ "$FAIL" -eq 0 ]; then
  echo "AUTOMATED VERIFICATION: PASS"
else
  echo "AUTOMATED VERIFICATION: FAIL"
fi
exit "$FAIL"
